Repository shipwright-io/setup, pull requests merged in 2022-11, with the labels that each got.

#7 Patching Container Registry Hostname in /etc/hosts
  README.md
  action.yaml
  assert.sh
  patch-etc-hosts.sh
Labels: kind/feature, lgtm, approved, release-note

#6 Skipping Steps with `_ignore` Input Value
  README.md
  action.yaml
Labels: lgtm, approved, kind/design, release-note

#9 Automatically create tags on push to main branch
  .github/workflows/release.yaml
  hack/release.sh
Labels: lgtm, approved, release-note
